[workspace]
members = [
    "slimchain-common",
]
exclude = [
    "rust-sgx-sdk",
]

[profile.release]
lto = true
opt-level = 3

[profile.dev]
lto = "off"
opt-level = 0

[profile.test]
lto = "off"
opt-level = 0
