[package]
name = "slimchain-network"
version = "0.1.0"
authors = ["Cheng XU <rust@xuc.me>"]
edition = "2018"
publish = false

[dependencies]
async-trait = "0.1"
bs58 = "0.4"
futures = "0.3"
# libp2p = "0.32.1"
libp2p = { git = "https://github.com/xu-cheng/rust-libp2p.git", rev = "7102bbde4966b4a995bc45357fe638331e90026e" }
once_cell = "1.5"
pin-project = "1.0"
postcard = { version = "0.5", features = ["alloc"] }
rand = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slimchain-chain = { path = "../slimchain-chain" }
slimchain-common = { path = "../slimchain-common" }
slimchain-tx-engine = { path = "../slimchain-tx-engine" }
slimchain-tx-state = { path = "../slimchain-tx-state" }
slimchain-utils = { path = "../slimchain-utils" }
surf = "2.1"
tokio = { version = "0.2", features = ["full", "parking_lot"] }
tracing = "0.1"
tracing-futures = "0.2"
warp = "0.2"

[dev-dependencies]
serial_test = "0.5"
