[package]
name = "slimchain-network"
version = "0.1.0"
authors = ["Cheng XU <rust@xuc.me>"]
edition = "2018"
publish = false

[dependencies]
async-trait = "0.1"
bs58 = "0.3"
futures = "0.3"
libp2p = "0.28"
once_cell = "1.4"
pin-project = "0.4"
postcard = { version = "0.5", features = ["alloc"] }
rand = "0.7"
serde = { version = "1.0", features = ["derive"] }
slimchain-chain = { path = "../slimchain-chain" }
slimchain-common = { path = "../slimchain-common" }
slimchain-tx-engine = { path = "../slimchain-tx-engine" }
slimchain-tx-state = { path = "../slimchain-tx-state" }
slimchain-utils = { path = "../slimchain-utils" }
surf = "2.0.0-alpha.5"
tokio = { version = "0.2", features = ["full", "parking_lot"] }
tracing = "0.1"
tracing-futures = "0.2"
warp = "0.2"

[dev-dependencies]
serial_test = "0.5"
